name: Run Fullstack Tests

on: [push, pull_request]

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flask_app/requirements.txt
          pip install pytest pytest-flask

      - name: Run tests
        run: pytest

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./next_frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm ci

      - name: Lint frontend
        run: npm run lint

      - name: Build frontend
        run: npm run build

